import enum


class UserRole(enum.StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ORGANIZATION_ADMIN = "ORGANIZATION_ADMIN"
    SECURITY_ANALYST = "SECURITY_ANALYST"
    HELPDESK_OPERATOR = "HELPDESK_OPERATOR"
    READ_ONLY = "READ_ONLY"
