"""update_inventory_local_users_schema

Revision ID: 06675696d16d
Revises: 1298d34c15b2
Create Date: 2026-07-21 11:47:52.390131

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "06675696d16d"
down_revision: str | None = "1298d34c15b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inventory_local_users", sa.Column("sid", sa.String(length=255), nullable=False))
    op.add_column(
        "inventory_local_users", sa.Column("full_name", sa.String(length=512), nullable=True)
    )
    op.add_column("inventory_local_users", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "inventory_local_users", sa.Column("account_type", sa.String(length=100), nullable=True)
    )
    op.add_column("inventory_local_users", sa.Column("is_enabled", sa.Boolean(), nullable=True))
    op.add_column("inventory_local_users", sa.Column("is_locked", sa.Boolean(), nullable=True))
    op.add_column(
        "inventory_local_users", sa.Column("is_password_required", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "inventory_local_users",
        sa.Column("is_password_change_allowed", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "inventory_local_users", sa.Column("password_expires", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "inventory_local_users", sa.Column("password_never_expires", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "inventory_local_users",
        sa.Column("password_last_set", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "inventory_local_users", sa.Column("last_logon", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "inventory_local_users", sa.Column("last_logoff", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "inventory_local_users",
        sa.Column("account_created", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "inventory_local_users",
        sa.Column("account_expires", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "inventory_local_users", sa.Column("bad_logon_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "inventory_local_users", sa.Column("home_directory", sa.String(length=1024), nullable=True)
    )
    op.add_column(
        "inventory_local_users", sa.Column("profile_path", sa.String(length=1024), nullable=True)
    )
    op.add_column(
        "inventory_local_users", sa.Column("script_path", sa.String(length=1024), nullable=True)
    )
    op.add_column(
        "inventory_local_users", sa.Column("primary_group", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "inventory_local_users",
        sa.Column(
            "local_groups",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.add_column(
        "inventory_local_users", sa.Column("is_builtin_account", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "inventory_local_users", sa.Column("is_administrator", sa.Boolean(), nullable=True)
    )
    op.add_column("inventory_local_users", sa.Column("is_guest", sa.Boolean(), nullable=True))
    op.drop_index(op.f("ix_inventory_local_users_username"), table_name="inventory_local_users")
    op.create_index(
        op.f("ix_inventory_local_users_sid"), "inventory_local_users", ["sid"], unique=False
    )
    op.drop_column("inventory_local_users", "is_active")
    op.drop_column("inventory_local_users", "privilege")
    op.drop_column("inventory_local_users", "last_login")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventory_local_users",
        sa.Column(
            "last_login", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "inventory_local_users",
        sa.Column("privilege", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.add_column(
        "inventory_local_users",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_inventory_local_users_sid"), table_name="inventory_local_users")
    op.create_index(
        op.f("ix_inventory_local_users_username"),
        "inventory_local_users",
        ["username"],
        unique=False,
    )
    op.drop_column("inventory_local_users", "is_guest")
    op.drop_column("inventory_local_users", "is_administrator")
    op.drop_column("inventory_local_users", "is_builtin_account")
    op.drop_column("inventory_local_users", "local_groups")
    op.drop_column("inventory_local_users", "primary_group")
    op.drop_column("inventory_local_users", "script_path")
    op.drop_column("inventory_local_users", "profile_path")
    op.drop_column("inventory_local_users", "home_directory")
    op.drop_column("inventory_local_users", "bad_logon_count")
    op.drop_column("inventory_local_users", "account_expires")
    op.drop_column("inventory_local_users", "account_created")
    op.drop_column("inventory_local_users", "last_logoff")
    op.drop_column("inventory_local_users", "last_logon")
    op.drop_column("inventory_local_users", "password_last_set")
    op.drop_column("inventory_local_users", "password_never_expires")
    op.drop_column("inventory_local_users", "password_expires")
    op.drop_column("inventory_local_users", "is_password_change_allowed")
    op.drop_column("inventory_local_users", "is_password_required")
    op.drop_column("inventory_local_users", "is_locked")
    op.drop_column("inventory_local_users", "is_enabled")
    op.drop_column("inventory_local_users", "account_type")
    op.drop_column("inventory_local_users", "description")
    op.drop_column("inventory_local_users", "full_name")
    op.drop_column("inventory_local_users", "sid")
    # ### end Alembic commands ###
