"""update inventory services schema

Revision ID: 1298d34c15b2
Revises: dc89ad4c650f
Create Date: 2026-07-21 11:20:51.054083

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1298d34c15b2"
down_revision: str | None = "dc89ad4c650f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inventory_services", sa.Column("description", sa.String(), nullable=True))
    op.add_column(
        "inventory_services", sa.Column("service_type", sa.String(length=50), nullable=True)
    )
    op.add_column("inventory_services", sa.Column("binary_path", sa.String(), nullable=True))
    op.add_column(
        "inventory_services", sa.Column("service_account", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "inventory_services", sa.Column("delayed_auto_start", sa.Boolean(), nullable=True)
    )
    op.add_column("inventory_services", sa.Column("process_id", sa.Integer(), nullable=True))
    op.add_column(
        "inventory_services",
        sa.Column("dependencies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "inventory_services",
        sa.Column("dependent_services", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("inventory_services", sa.Column("accept_stop", sa.Boolean(), nullable=True))
    op.add_column("inventory_services", sa.Column("accept_pause", sa.Boolean(), nullable=True))
    op.add_column("inventory_services", sa.Column("can_shutdown", sa.Boolean(), nullable=True))
    op.add_column("inventory_services", sa.Column("exit_code", sa.Integer(), nullable=True))
    op.add_column("inventory_services", sa.Column("service_flags", sa.Integer(), nullable=True))
    op.add_column(
        "inventory_services", sa.Column("error_control", sa.String(length=50), nullable=True)
    )
    op.add_column("inventory_services", sa.Column("load_order_group", sa.String(), nullable=True))
    op.add_column("inventory_services", sa.Column("tag_id", sa.Integer(), nullable=True))
    op.add_column("inventory_services", sa.Column("trigger_start", sa.Boolean(), nullable=True))
    op.alter_column(
        "inventory_services",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inventory_services",
        "status",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.drop_column("inventory_services", "trigger_start")
    op.drop_column("inventory_services", "tag_id")
    op.drop_column("inventory_services", "load_order_group")
    op.drop_column("inventory_services", "error_control")
    op.drop_column("inventory_services", "service_flags")
    op.drop_column("inventory_services", "exit_code")
    op.drop_column("inventory_services", "can_shutdown")
    op.drop_column("inventory_services", "accept_pause")
    op.drop_column("inventory_services", "accept_stop")
    op.drop_column("inventory_services", "dependent_services")
    op.drop_column("inventory_services", "dependencies")
    op.drop_column("inventory_services", "process_id")
    op.drop_column("inventory_services", "delayed_auto_start")
    op.drop_column("inventory_services", "service_account")
    op.drop_column("inventory_services", "binary_path")
    op.drop_column("inventory_services", "service_type")
    op.drop_column("inventory_services", "description")
    # ### end Alembic commands ###
