"""add_storage_collector_tables

Revision ID: 29c437a306be
Revises: ce4123b887c7
Create Date: 2026-07-21 08:56:21.448576

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29c437a306be"
down_revision: str | None = "ce4123b887c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_storage_pools",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("pool_name", sa.String(), nullable=False),
        sa.Column("health_status", sa.String(length=50), nullable=True),
        sa.Column("operational_status", sa.String(length=50), nullable=True),
        sa.Column("total_capacity", sa.BigInteger(), nullable=True),
        sa.Column("free_capacity", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_storage_pools_endpoint_id"),
        "inventory_storage_pools",
        ["endpoint_id"],
        unique=False,
    )
    op.create_table(
        "inventory_disk_smart",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("disk_id", sa.Integer(), nullable=False),
        sa.Column("predict_failure", sa.Boolean(), nullable=True),
        sa.Column("temperature", sa.Integer(), nullable=True),
        sa.Column("wear_level", sa.Integer(), nullable=True),
        sa.Column("remaining_life", sa.Integer(), nullable=True),
        sa.Column("reallocated_sector_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["disk_id"], ["inventory_disks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_disk_smart_disk_id"), "inventory_disk_smart", ["disk_id"], unique=True
    )
    op.create_table(
        "inventory_partitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("disk_id", sa.Integer(), nullable=False),
        sa.Column("volume_id", sa.Integer(), nullable=True),
        sa.Column("partition_number", sa.Integer(), nullable=True),
        sa.Column("partition_style", sa.String(length=50), nullable=True),
        sa.Column("partition_type", sa.String(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("offset_bytes", sa.BigInteger(), nullable=True),
        sa.Column("drive_letter", sa.String(length=10), nullable=True),
        sa.Column("is_boot", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_hidden", sa.Boolean(), nullable=True),
        sa.Column("is_read_only", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["disk_id"], ["inventory_disks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["volume_id"], ["inventory_volumes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_partitions_disk_id"), "inventory_partitions", ["disk_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_partitions_endpoint_id"),
        "inventory_partitions",
        ["endpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_partitions_volume_id"),
        "inventory_partitions",
        ["volume_id"],
        unique=False,
    )
    op.create_table(
        "inventory_virtual_disks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("pool_id", sa.Integer(), nullable=False),
        sa.Column("virtual_disk_name", sa.String(), nullable=False),
        sa.Column("resiliency_type", sa.String(length=50), nullable=True),
        sa.Column("provisioning_type", sa.String(length=50), nullable=True),
        sa.Column("health_status", sa.String(length=50), nullable=True),
        sa.Column("operational_status", sa.String(length=50), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pool_id"], ["inventory_storage_pools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_virtual_disks_endpoint_id"),
        "inventory_virtual_disks",
        ["endpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_virtual_disks_pool_id"),
        "inventory_virtual_disks",
        ["pool_id"],
        unique=False,
    )
    op.create_table(
        "inventory_volume_mounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("volume_id", sa.Integer(), nullable=False),
        sa.Column("mount_path", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["volume_id"], ["inventory_volumes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_volume_mounts_endpoint_id"),
        "inventory_volume_mounts",
        ["endpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_volume_mounts_volume_id"),
        "inventory_volume_mounts",
        ["volume_id"],
        unique=False,
    )
    op.add_column("inventory_disks", sa.Column("device_name", sa.String(), nullable=True))
    op.add_column("inventory_disks", sa.Column("friendly_name", sa.String(), nullable=True))
    op.add_column("inventory_disks", sa.Column("manufacturer", sa.String(), nullable=True))
    op.add_column("inventory_disks", sa.Column("firmware_version", sa.String(), nullable=True))
    op.add_column("inventory_disks", sa.Column("bus_type", sa.String(length=50), nullable=True))
    op.add_column("inventory_disks", sa.Column("media_type", sa.String(length=50), nullable=True))
    op.add_column(
        "inventory_disks", sa.Column("health_status", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "inventory_disks", sa.Column("operational_status", sa.String(length=50), nullable=True)
    )
    op.add_column("inventory_disks", sa.Column("logical_sector_size", sa.Integer(), nullable=True))
    op.add_column("inventory_disks", sa.Column("physical_sector_size", sa.Integer(), nullable=True))
    op.add_column("inventory_disks", sa.Column("rotation_rate", sa.Integer(), nullable=True))
    op.add_column("inventory_disks", sa.Column("is_removable", sa.Boolean(), nullable=True))
    op.add_column("inventory_disks", sa.Column("is_boot_disk", sa.Boolean(), nullable=True))
    op.add_column("inventory_disks", sa.Column("is_system_disk", sa.Boolean(), nullable=True))
    op.add_column("inventory_disks", sa.Column("unique_id", sa.String(), nullable=True))
    op.add_column("inventory_disks", sa.Column("location", sa.String(), nullable=True))
    op.add_column(
        "inventory_disks", sa.Column("partition_style", sa.String(length=50), nullable=True)
    )
    op.add_column("inventory_disks", sa.Column("is_offline", sa.Boolean(), nullable=True))
    op.add_column("inventory_disks", sa.Column("is_read_only", sa.Boolean(), nullable=True))
    op.add_column("inventory_disks", sa.Column("can_pool", sa.Boolean(), nullable=True))
    op.add_column("inventory_volumes", sa.Column("volume_name", sa.String(), nullable=True))
    op.add_column(
        "inventory_volumes", sa.Column("file_system", sa.String(length=50), nullable=True)
    )
    op.add_column("inventory_volumes", sa.Column("file_system_label", sa.String(), nullable=True))
    op.add_column("inventory_volumes", sa.Column("file_system_version", sa.String(), nullable=True))
    op.add_column(
        "inventory_volumes", sa.Column("allocation_unit_size", sa.Integer(), nullable=True)
    )
    op.add_column("inventory_volumes", sa.Column("total_size", sa.BigInteger(), nullable=True))
    op.add_column("inventory_volumes", sa.Column("free_space", sa.BigInteger(), nullable=True))
    op.add_column("inventory_volumes", sa.Column("used_space", sa.BigInteger(), nullable=True))
    op.add_column("inventory_volumes", sa.Column("percentage_used", sa.Float(), nullable=True))
    op.add_column("inventory_volumes", sa.Column("percentage_free", sa.Float(), nullable=True))
    op.add_column(
        "inventory_volumes", sa.Column("health_status", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "inventory_volumes", sa.Column("compression_enabled", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "inventory_volumes", sa.Column("deduplication_enabled", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "inventory_volumes", sa.Column("shadow_copies_enabled", sa.Boolean(), nullable=True)
    )
    op.drop_column("inventory_volumes", "filesystem")
    op.drop_column("inventory_volumes", "size_bytes")
    op.drop_column("inventory_volumes", "label")
    op.drop_column("inventory_volumes", "free_bytes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventory_volumes",
        sa.Column("free_bytes", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "inventory_volumes", sa.Column("label", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "inventory_volumes",
        sa.Column("size_bytes", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "inventory_volumes",
        sa.Column("filesystem", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_column("inventory_volumes", "shadow_copies_enabled")
    op.drop_column("inventory_volumes", "deduplication_enabled")
    op.drop_column("inventory_volumes", "compression_enabled")
    op.drop_column("inventory_volumes", "health_status")
    op.drop_column("inventory_volumes", "percentage_free")
    op.drop_column("inventory_volumes", "percentage_used")
    op.drop_column("inventory_volumes", "used_space")
    op.drop_column("inventory_volumes", "free_space")
    op.drop_column("inventory_volumes", "total_size")
    op.drop_column("inventory_volumes", "allocation_unit_size")
    op.drop_column("inventory_volumes", "file_system_version")
    op.drop_column("inventory_volumes", "file_system_label")
    op.drop_column("inventory_volumes", "file_system")
    op.drop_column("inventory_volumes", "volume_name")
    op.drop_column("inventory_disks", "can_pool")
    op.drop_column("inventory_disks", "is_read_only")
    op.drop_column("inventory_disks", "is_offline")
    op.drop_column("inventory_disks", "partition_style")
    op.drop_column("inventory_disks", "location")
    op.drop_column("inventory_disks", "unique_id")
    op.drop_column("inventory_disks", "is_system_disk")
    op.drop_column("inventory_disks", "is_boot_disk")
    op.drop_column("inventory_disks", "is_removable")
    op.drop_column("inventory_disks", "rotation_rate")
    op.drop_column("inventory_disks", "physical_sector_size")
    op.drop_column("inventory_disks", "logical_sector_size")
    op.drop_column("inventory_disks", "operational_status")
    op.drop_column("inventory_disks", "health_status")
    op.drop_column("inventory_disks", "media_type")
    op.drop_column("inventory_disks", "bus_type")
    op.drop_column("inventory_disks", "firmware_version")
    op.drop_column("inventory_disks", "manufacturer")
    op.drop_column("inventory_disks", "friendly_name")
    op.drop_column("inventory_disks", "device_name")
    op.drop_index(
        op.f("ix_inventory_volume_mounts_volume_id"), table_name="inventory_volume_mounts"
    )
    op.drop_index(
        op.f("ix_inventory_volume_mounts_endpoint_id"), table_name="inventory_volume_mounts"
    )
    op.drop_table("inventory_volume_mounts")
    op.drop_index(op.f("ix_inventory_virtual_disks_pool_id"), table_name="inventory_virtual_disks")
    op.drop_index(
        op.f("ix_inventory_virtual_disks_endpoint_id"), table_name="inventory_virtual_disks"
    )
    op.drop_table("inventory_virtual_disks")
    op.drop_index(op.f("ix_inventory_partitions_volume_id"), table_name="inventory_partitions")
    op.drop_index(op.f("ix_inventory_partitions_endpoint_id"), table_name="inventory_partitions")
    op.drop_index(op.f("ix_inventory_partitions_disk_id"), table_name="inventory_partitions")
    op.drop_table("inventory_partitions")
    op.drop_index(op.f("ix_inventory_disk_smart_disk_id"), table_name="inventory_disk_smart")
    op.drop_table("inventory_disk_smart")
    op.drop_index(
        op.f("ix_inventory_storage_pools_endpoint_id"), table_name="inventory_storage_pools"
    )
    op.drop_table("inventory_storage_pools")
    # ### end Alembic commands ###
