"""add_defender_features

Revision ID: 4331008ba2e1
Revises: aca0c69b0de0
Create Date: 2026-07-22 19:05:45.639292

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4331008ba2e1'
down_revision: str | None = 'aca0c69b0de0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_security_status', sa.Column('defender_exploit_protection', sa.Boolean(), nullable=True))
    op.add_column('inventory_security_status', sa.Column('defender_controlled_folder_access', sa.Boolean(), nullable=True))
    op.add_column('inventory_security_status', sa.Column('defender_boot_protection', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_security_status', 'defender_boot_protection')
    op.drop_column('inventory_security_status', 'defender_controlled_folder_access')
    op.drop_column('inventory_security_status', 'defender_exploit_protection')
    # ### end Alembic commands ###
