"""expand_os_inventory

Revision ID: 5d3fedc2e6ee
Revises: a64f2c754869
Create Date: 2026-07-21 07:40:18.452321

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d3fedc2e6ee"
down_revision: str | None = "a64f2c754869"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inventory_os", sa.Column("edition", sa.String(), nullable=True))
    op.add_column("inventory_os", sa.Column("display_version", sa.String(), nullable=True))
    op.add_column(
        "inventory_os", sa.Column("last_boot_time", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("inventory_os", sa.Column("system_uptime_seconds", sa.Integer(), nullable=True))
    op.add_column("inventory_os", sa.Column("computer_name", sa.String(), nullable=True))
    op.add_column("inventory_os", sa.Column("domain", sa.String(), nullable=True))
    op.add_column("inventory_os", sa.Column("registered_owner", sa.String(), nullable=True))
    op.add_column("inventory_os", sa.Column("time_zone", sa.String(), nullable=True))
    op.add_column("inventory_os", sa.Column("system_locale", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inventory_os", "system_locale")
    op.drop_column("inventory_os", "time_zone")
    op.drop_column("inventory_os", "registered_owner")
    op.drop_column("inventory_os", "domain")
    op.drop_column("inventory_os", "computer_name")
    op.drop_column("inventory_os", "system_uptime_seconds")
    op.drop_column("inventory_os", "last_boot_time")
    op.drop_column("inventory_os", "display_version")
    op.drop_column("inventory_os", "edition")
    # ### end Alembic commands ###
