"""add_software_collector_tables

Revision ID: 8aa94f375830
Revises: 29c437a306be
Create Date: 2026-07-21 10:11:45.716014

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8aa94f375830"
down_revision: str | None = "29c437a306be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inventory_software", sa.Column("install_location", sa.String(), nullable=True))
    op.add_column("inventory_software", sa.Column("install_source", sa.String(), nullable=True))
    op.add_column(
        "inventory_software", sa.Column("estimated_size_bytes", sa.BigInteger(), nullable=True)
    )
    op.add_column("inventory_software", sa.Column("uninstall_string", sa.String(), nullable=True))
    op.add_column(
        "inventory_software", sa.Column("quiet_uninstall_string", sa.String(), nullable=True)
    )
    op.add_column("inventory_software", sa.Column("install_scope", sa.String(), nullable=True))
    op.add_column("inventory_software", sa.Column("architecture", sa.String(), nullable=True))
    op.add_column("inventory_software", sa.Column("product_code", sa.String(), nullable=True))
    op.add_column("inventory_software", sa.Column("help_link", sa.String(), nullable=True))
    op.add_column("inventory_software", sa.Column("url_info_about", sa.String(), nullable=True))
    op.add_column("inventory_software", sa.Column("url_update_info", sa.String(), nullable=True))
    op.add_column("inventory_software", sa.Column("display_icon", sa.String(), nullable=True))
    op.add_column("inventory_software", sa.Column("language", sa.String(), nullable=True))
    op.add_column("inventory_software", sa.Column("release_type", sa.String(), nullable=True))
    op.add_column("inventory_software", sa.Column("parent_application", sa.String(), nullable=True))
    op.add_column("inventory_software", sa.Column("parent_version", sa.String(), nullable=True))
    op.add_column("inventory_software", sa.Column("system_component", sa.Boolean(), nullable=False))
    op.add_column(
        "inventory_software", sa.Column("windows_installer", sa.Boolean(), nullable=False)
    )
    op.add_column("inventory_software", sa.Column("no_remove", sa.Boolean(), nullable=False))
    op.add_column("inventory_software", sa.Column("no_modify", sa.Boolean(), nullable=False))
    op.add_column("inventory_software", sa.Column("no_repair", sa.Boolean(), nullable=False))
    op.add_column("inventory_software", sa.Column("classification", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_inventory_software_product_code"),
        "inventory_software",
        ["product_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_software_publisher"), "inventory_software", ["publisher"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_software_publisher"), table_name="inventory_software")
    op.drop_index(op.f("ix_inventory_software_product_code"), table_name="inventory_software")
    op.drop_column("inventory_software", "classification")
    op.drop_column("inventory_software", "no_repair")
    op.drop_column("inventory_software", "no_modify")
    op.drop_column("inventory_software", "no_remove")
    op.drop_column("inventory_software", "windows_installer")
    op.drop_column("inventory_software", "system_component")
    op.drop_column("inventory_software", "parent_version")
    op.drop_column("inventory_software", "parent_application")
    op.drop_column("inventory_software", "release_type")
    op.drop_column("inventory_software", "language")
    op.drop_column("inventory_software", "display_icon")
    op.drop_column("inventory_software", "url_update_info")
    op.drop_column("inventory_software", "url_info_about")
    op.drop_column("inventory_software", "help_link")
    op.drop_column("inventory_software", "product_code")
    op.drop_column("inventory_software", "architecture")
    op.drop_column("inventory_software", "install_scope")
    op.drop_column("inventory_software", "quiet_uninstall_string")
    op.drop_column("inventory_software", "uninstall_string")
    op.drop_column("inventory_software", "estimated_size_bytes")
    op.drop_column("inventory_software", "install_source")
    op.drop_column("inventory_software", "install_location")
    # ### end Alembic commands ###
