"""Add performance_history table

Revision ID: 8f8a330bae53
Revises: 72dccbaf6031
Create Date: 2026-07-22 22:19:46.520613

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8a330bae53'
down_revision: Union[str, None] = '72dccbaf6031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_history',
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=False),
    sa.Column('memory_usage_percent', sa.Float(), nullable=False),
    sa.Column('disk_usage_percent', sa.Float(), nullable=False),
    sa.Column('network_in_bytes', sa.BigInteger(), nullable=False),
    sa.Column('network_out_bytes', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_performance_history_endpoint_id'), 'performance_history', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_performance_history_timestamp'), 'performance_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_history_timestamp'), table_name='performance_history')
    op.drop_index(op.f('ix_performance_history_endpoint_id'), table_name='performance_history')
    op.drop_table('performance_history')
    # ### end Alembic commands ###
