"""create_inventory_schema

Revision ID: a64f2c754869
Revises: 6d119a97f264
Create Date: 2026-07-21 02:37:24.646401

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a64f2c754869"
down_revision: str | None = "6d119a97f264"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_category_states",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("inventory_hash", sa.String(), nullable=False),
        sa.Column("agent_version", sa.String(), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint_id", "category", name="uq_category_state"),
    )
    op.create_index(
        op.f("ix_inventory_category_states_endpoint_id"),
        "inventory_category_states",
        ["endpoint_id"],
        unique=False,
    )
    op.create_table(
        "inventory_disks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("serial_number", sa.String(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("interface_type", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_disks_endpoint_id"), "inventory_disks", ["endpoint_id"], unique=False
    )
    op.create_table(
        "inventory_hardware",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("cpu_model", sa.String(), nullable=False),
        sa.Column("cpu_cores", sa.Integer(), nullable=False),
        sa.Column("cpu_threads", sa.Integer(), nullable=False),
        sa.Column("total_ram_bytes", sa.BigInteger(), nullable=False),
        sa.Column("system_manufacturer", sa.String(), nullable=True),
        sa.Column("system_model", sa.String(), nullable=True),
        sa.Column("bios_version", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_hardware_endpoint_id"),
        "inventory_hardware",
        ["endpoint_id"],
        unique=True,
    )
    op.create_table(
        "inventory_local_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("privilege", sa.String(length=50), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_local_users_endpoint_id"),
        "inventory_local_users",
        ["endpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_local_users_username"),
        "inventory_local_users",
        ["username"],
        unique=False,
    )
    op.create_table(
        "inventory_network_adapters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("mac_address", sa.String(), nullable=True),
        sa.Column("is_physical", sa.Boolean(), nullable=False),
        sa.Column("is_virtual", sa.Boolean(), nullable=False),
        sa.Column("adapter_type", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_network_adapters_endpoint_id"),
        "inventory_network_adapters",
        ["endpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_network_adapters_mac_address"),
        "inventory_network_adapters",
        ["mac_address"],
        unique=False,
    )
    op.create_table(
        "inventory_os",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("build_number", sa.String(), nullable=True),
        sa.Column("architecture", sa.String(), nullable=False),
        sa.Column("install_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_os_endpoint_id"), "inventory_os", ["endpoint_id"], unique=True
    )
    op.create_table(
        "inventory_security_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("antivirus_name", sa.String(), nullable=True),
        sa.Column("antivirus_status", sa.String(), nullable=True),
        sa.Column("firewall_enabled", sa.Boolean(), nullable=True),
        sa.Column("bitlocker_enabled", sa.Boolean(), nullable=True),
        sa.Column("secure_boot_enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_security_status_endpoint_id"),
        "inventory_security_status",
        ["endpoint_id"],
        unique=True,
    )
    op.create_table(
        "inventory_services",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("startup_type", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_services_endpoint_id"),
        "inventory_services",
        ["endpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_services_name"), "inventory_services", ["name"], unique=False
    )
    op.create_table(
        "inventory_software",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("publisher", sa.String(), nullable=True),
        sa.Column("install_date", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_software_endpoint_id"),
        "inventory_software",
        ["endpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_software_name"), "inventory_software", ["name"], unique=False
    )
    op.create_table(
        "inventory_sync_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("inventory_hash", sa.String(), nullable=True),
        sa.Column("agent_version", sa.String(), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_sync_logs_category"), "inventory_sync_logs", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_sync_logs_endpoint_id"),
        "inventory_sync_logs",
        ["endpoint_id"],
        unique=False,
    )
    op.create_table(
        "inventory_volumes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("drive_letter", sa.String(length=10), nullable=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("filesystem", sa.String(length=50), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("free_bytes", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_volumes_endpoint_id"), "inventory_volumes", ["endpoint_id"], unique=False
    )
    op.create_table(
        "inventory_windows_updates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("kb_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("install_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_windows_updates_endpoint_id"),
        "inventory_windows_updates",
        ["endpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_windows_updates_kb_id"),
        "inventory_windows_updates",
        ["kb_id"],
        unique=False,
    )
    op.create_table(
        "inventory_network_addresses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("adapter_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("family", sa.String(length=10), nullable=False),
        sa.Column("prefix_length", sa.Integer(), nullable=True),
        sa.Column("is_loopback", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["adapter_id"], ["inventory_network_adapters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_network_addresses_adapter_id"),
        "inventory_network_addresses",
        ["adapter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_network_addresses_address"),
        "inventory_network_addresses",
        ["address"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_inventory_network_addresses_address"), table_name="inventory_network_addresses"
    )
    op.drop_index(
        op.f("ix_inventory_network_addresses_adapter_id"), table_name="inventory_network_addresses"
    )
    op.drop_table("inventory_network_addresses")
    op.drop_index(
        op.f("ix_inventory_windows_updates_kb_id"), table_name="inventory_windows_updates"
    )
    op.drop_index(
        op.f("ix_inventory_windows_updates_endpoint_id"), table_name="inventory_windows_updates"
    )
    op.drop_table("inventory_windows_updates")
    op.drop_index(op.f("ix_inventory_volumes_endpoint_id"), table_name="inventory_volumes")
    op.drop_table("inventory_volumes")
    op.drop_index(op.f("ix_inventory_sync_logs_endpoint_id"), table_name="inventory_sync_logs")
    op.drop_index(op.f("ix_inventory_sync_logs_category"), table_name="inventory_sync_logs")
    op.drop_table("inventory_sync_logs")
    op.drop_index(op.f("ix_inventory_software_name"), table_name="inventory_software")
    op.drop_index(op.f("ix_inventory_software_endpoint_id"), table_name="inventory_software")
    op.drop_table("inventory_software")
    op.drop_index(op.f("ix_inventory_services_name"), table_name="inventory_services")
    op.drop_index(op.f("ix_inventory_services_endpoint_id"), table_name="inventory_services")
    op.drop_table("inventory_services")
    op.drop_index(
        op.f("ix_inventory_security_status_endpoint_id"), table_name="inventory_security_status"
    )
    op.drop_table("inventory_security_status")
    op.drop_index(op.f("ix_inventory_os_endpoint_id"), table_name="inventory_os")
    op.drop_table("inventory_os")
    op.drop_index(
        op.f("ix_inventory_network_adapters_mac_address"), table_name="inventory_network_adapters"
    )
    op.drop_index(
        op.f("ix_inventory_network_adapters_endpoint_id"), table_name="inventory_network_adapters"
    )
    op.drop_table("inventory_network_adapters")
    op.drop_index(op.f("ix_inventory_local_users_username"), table_name="inventory_local_users")
    op.drop_index(op.f("ix_inventory_local_users_endpoint_id"), table_name="inventory_local_users")
    op.drop_table("inventory_local_users")
    op.drop_index(op.f("ix_inventory_hardware_endpoint_id"), table_name="inventory_hardware")
    op.drop_table("inventory_hardware")
    op.drop_index(op.f("ix_inventory_disks_endpoint_id"), table_name="inventory_disks")
    op.drop_table("inventory_disks")
    op.drop_index(
        op.f("ix_inventory_category_states_endpoint_id"), table_name="inventory_category_states"
    )
    op.drop_table("inventory_category_states")
    # ### end Alembic commands ###
