"""add_security_tables

Revision ID: b6968b9483cf
Revises: 5d3fedc2e6ee
Create Date: 2026-07-21 08:04:17.512813

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6968b9483cf"
down_revision: str | None = "5d3fedc2e6ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_bitlocker_volumes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("drive_letter", sa.String(), nullable=False),
        sa.Column("volume_type", sa.String(), nullable=True),
        sa.Column("protection_status", sa.String(), nullable=True),
        sa.Column("encryption_percentage", sa.Float(), nullable=True),
        sa.Column("encryption_method", sa.String(), nullable=True),
        sa.Column("lock_status", sa.String(), nullable=True),
        sa.Column("auto_unlock", sa.Boolean(), nullable=True),
        sa.Column("key_protector_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_bitlocker_volumes_endpoint_id"),
        "inventory_bitlocker_volumes",
        ["endpoint_id"],
        unique=False,
    )
    op.create_table(
        "inventory_firewall_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("endpoint_id", sa.Integer(), nullable=False),
        sa.Column("profile_name", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("default_inbound_policy", sa.String(), nullable=True),
        sa.Column("default_outbound_policy", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_firewall_profiles_endpoint_id"),
        "inventory_firewall_profiles",
        ["endpoint_id"],
        unique=False,
    )
    op.add_column(
        "inventory_security_status", sa.Column("defender_installed", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "inventory_security_status", sa.Column("defender_enabled", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "inventory_security_status", sa.Column("defender_rtp", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "inventory_security_status", sa.Column("defender_sig_version", sa.String(), nullable=True)
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("defender_engine_version", sa.String(), nullable=True),
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("defender_last_sig_update", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("defender_last_quick_scan", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("defender_last_full_scan", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "inventory_security_status", sa.Column("defender_av_enabled", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("defender_antispyware_enabled", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "inventory_security_status", sa.Column("defender_nis_enabled", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("defender_ioav_protection", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("defender_behavior_monitoring", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("defender_tamper_protection", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "inventory_security_status", sa.Column("tpm_present", sa.Boolean(), nullable=False)
    )
    op.add_column("inventory_security_status", sa.Column("tpm_ready", sa.Boolean(), nullable=False))
    op.add_column(
        "inventory_security_status", sa.Column("tpm_enabled", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "inventory_security_status", sa.Column("tpm_activated", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "inventory_security_status", sa.Column("tpm_manufacturer", sa.String(), nullable=True)
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("tpm_manufacturer_version", sa.String(), nullable=True),
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("tpm_specification_version", sa.String(), nullable=True),
    )
    op.add_column(
        "inventory_security_status", sa.Column("tpm_managed_auth_level", sa.String(), nullable=True)
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("secure_boot_supported", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "inventory_security_status", sa.Column("uac_enabled", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("uac_consent_prompt_behavior", sa.String(), nullable=True),
    )
    op.add_column(
        "inventory_security_status", sa.Column("security_center_status", sa.String(), nullable=True)
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("security_center_registered_av", sa.String(), nullable=True),
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("security_center_registered_fw", sa.String(), nullable=True),
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("security_center_registered_antispyware", sa.String(), nullable=True),
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("security_center_product_state", sa.Integer(), nullable=True),
    )
    op.alter_column(
        "inventory_security_status",
        "secure_boot_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.drop_column("inventory_security_status", "bitlocker_enabled")
    op.drop_column("inventory_security_status", "antivirus_name")
    op.drop_column("inventory_security_status", "firewall_enabled")
    op.drop_column("inventory_security_status", "antivirus_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventory_security_status",
        sa.Column("antivirus_status", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("firewall_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("antivirus_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "inventory_security_status",
        sa.Column("bitlocker_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "inventory_security_status",
        "secure_boot_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.drop_column("inventory_security_status", "security_center_product_state")
    op.drop_column("inventory_security_status", "security_center_registered_antispyware")
    op.drop_column("inventory_security_status", "security_center_registered_fw")
    op.drop_column("inventory_security_status", "security_center_registered_av")
    op.drop_column("inventory_security_status", "security_center_status")
    op.drop_column("inventory_security_status", "uac_consent_prompt_behavior")
    op.drop_column("inventory_security_status", "uac_enabled")
    op.drop_column("inventory_security_status", "secure_boot_supported")
    op.drop_column("inventory_security_status", "tpm_managed_auth_level")
    op.drop_column("inventory_security_status", "tpm_specification_version")
    op.drop_column("inventory_security_status", "tpm_manufacturer_version")
    op.drop_column("inventory_security_status", "tpm_manufacturer")
    op.drop_column("inventory_security_status", "tpm_activated")
    op.drop_column("inventory_security_status", "tpm_enabled")
    op.drop_column("inventory_security_status", "tpm_ready")
    op.drop_column("inventory_security_status", "tpm_present")
    op.drop_column("inventory_security_status", "defender_tamper_protection")
    op.drop_column("inventory_security_status", "defender_behavior_monitoring")
    op.drop_column("inventory_security_status", "defender_ioav_protection")
    op.drop_column("inventory_security_status", "defender_nis_enabled")
    op.drop_column("inventory_security_status", "defender_antispyware_enabled")
    op.drop_column("inventory_security_status", "defender_av_enabled")
    op.drop_column("inventory_security_status", "defender_last_full_scan")
    op.drop_column("inventory_security_status", "defender_last_quick_scan")
    op.drop_column("inventory_security_status", "defender_last_sig_update")
    op.drop_column("inventory_security_status", "defender_engine_version")
    op.drop_column("inventory_security_status", "defender_sig_version")
    op.drop_column("inventory_security_status", "defender_rtp")
    op.drop_column("inventory_security_status", "defender_enabled")
    op.drop_column("inventory_security_status", "defender_installed")
    op.drop_index(
        op.f("ix_inventory_firewall_profiles_endpoint_id"), table_name="inventory_firewall_profiles"
    )
    op.drop_table("inventory_firewall_profiles")
    op.drop_index(
        op.f("ix_inventory_bitlocker_volumes_endpoint_id"), table_name="inventory_bitlocker_volumes"
    )
    op.drop_table("inventory_bitlocker_volumes")
    # ### end Alembic commands ###
