"""add_network_collector_tables

Revision ID: ce4123b887c7
Revises: b6968b9483cf
Create Date: 2026-07-21 08:20:31.556306

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ce4123b887c7"
down_revision: str | None = "b6968b9483cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_network_vpn",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("adapter_id", sa.Integer(), nullable=False),
        sa.Column("connection_status", sa.String(), nullable=True),
        sa.Column("tunnel_type", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["adapter_id"], ["inventory_network_adapters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_network_vpn_adapter_id"),
        "inventory_network_vpn",
        ["adapter_id"],
        unique=True,
    )
    op.create_table(
        "inventory_network_wifi",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("adapter_id", sa.Integer(), nullable=False),
        sa.Column("ssid", sa.String(), nullable=True),
        sa.Column("bssid", sa.String(), nullable=True),
        sa.Column("signal_strength", sa.Integer(), nullable=True),
        sa.Column("auth_type", sa.String(), nullable=True),
        sa.Column("radio_type", sa.String(), nullable=True),
        sa.Column("channel", sa.Integer(), nullable=True),
        sa.Column("frequency_mhz", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["adapter_id"], ["inventory_network_adapters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_network_wifi_adapter_id"),
        "inventory_network_wifi",
        ["adapter_id"],
        unique=True,
    )
    op.add_column("endpoints", sa.Column("fqdn", sa.String(), nullable=True))
    op.add_column("endpoints", sa.Column("domain_workgroup", sa.String(), nullable=True))
    op.add_column("endpoints", sa.Column("primary_dns_suffix", sa.String(), nullable=True))
    op.add_column(
        "inventory_network_adapters", sa.Column("friendly_name", sa.String(), nullable=True)
    )
    op.add_column(
        "inventory_network_adapters", sa.Column("description", sa.String(), nullable=True)
    )
    op.add_column(
        "inventory_network_adapters", sa.Column("interface_type", sa.String(), nullable=True)
    )
    op.add_column(
        "inventory_network_adapters", sa.Column("manufacturer", sa.String(), nullable=True)
    )
    op.add_column(
        "inventory_network_adapters", sa.Column("admin_status", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "inventory_network_adapters", sa.Column("link_speed_bps", sa.BigInteger(), nullable=True)
    )
    op.add_column("inventory_network_adapters", sa.Column("mtu", sa.Integer(), nullable=True))
    op.add_column(
        "inventory_network_adapters", sa.Column("driver_version", sa.String(), nullable=True)
    )
    op.add_column("inventory_network_adapters", sa.Column("driver_date", sa.Date(), nullable=True))
    op.add_column(
        "inventory_network_adapters", sa.Column("interface_index", sa.Integer(), nullable=True)
    )
    op.add_column(
        "inventory_network_adapters", sa.Column("interface_guid", sa.String(), nullable=True)
    )
    op.add_column(
        "inventory_network_adapters", sa.Column("dhcp_enabled", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "inventory_network_adapters", sa.Column("dhcp_server", sa.String(), nullable=True)
    )
    op.add_column(
        "inventory_network_adapters",
        sa.Column("dhcp_lease_obtained", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "inventory_network_adapters",
        sa.Column("dhcp_lease_expires", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "inventory_network_adapters",
        sa.Column("default_gateways", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "inventory_network_adapters",
        sa.Column("dns_servers", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "inventory_network_adapters",
        sa.Column("dns_search_suffixes", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "inventory_network_addresses", sa.Column("subnet_mask", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inventory_network_addresses", "subnet_mask")
    op.drop_column("inventory_network_adapters", "dns_search_suffixes")
    op.drop_column("inventory_network_adapters", "dns_servers")
    op.drop_column("inventory_network_adapters", "default_gateways")
    op.drop_column("inventory_network_adapters", "dhcp_lease_expires")
    op.drop_column("inventory_network_adapters", "dhcp_lease_obtained")
    op.drop_column("inventory_network_adapters", "dhcp_server")
    op.drop_column("inventory_network_adapters", "dhcp_enabled")
    op.drop_column("inventory_network_adapters", "interface_guid")
    op.drop_column("inventory_network_adapters", "interface_index")
    op.drop_column("inventory_network_adapters", "driver_date")
    op.drop_column("inventory_network_adapters", "driver_version")
    op.drop_column("inventory_network_adapters", "mtu")
    op.drop_column("inventory_network_adapters", "link_speed_bps")
    op.drop_column("inventory_network_adapters", "admin_status")
    op.drop_column("inventory_network_adapters", "manufacturer")
    op.drop_column("inventory_network_adapters", "interface_type")
    op.drop_column("inventory_network_adapters", "description")
    op.drop_column("inventory_network_adapters", "friendly_name")
    op.drop_column("endpoints", "primary_dns_suffix")
    op.drop_column("endpoints", "domain_workgroup")
    op.drop_column("endpoints", "fqdn")
    op.drop_index(op.f("ix_inventory_network_wifi_adapter_id"), table_name="inventory_network_wifi")
    op.drop_table("inventory_network_wifi")
    op.drop_index(op.f("ix_inventory_network_vpn_adapter_id"), table_name="inventory_network_vpn")
    op.drop_table("inventory_network_vpn")
    # ### end Alembic commands ###
