"""Update inventory_windows_updates schema

Revision ID: dc89ad4c650f
Revises: 8aa94f375830
Create Date: 2026-07-21 10:47:27.860365

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dc89ad4c650f"
down_revision: str | None = "8aa94f375830"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inventory_windows_updates", sa.Column("hotfix_id", sa.String(), nullable=True))
    op.add_column("inventory_windows_updates", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "inventory_windows_updates", sa.Column("classification", sa.String(), nullable=True)
    )
    op.add_column(
        "inventory_windows_updates", sa.Column("installed_by", sa.String(), nullable=True)
    )
    op.add_column(
        "inventory_windows_updates",
        sa.Column("installed_on", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "inventory_windows_updates", sa.Column("installation_state", sa.String(), nullable=True)
    )
    op.add_column("inventory_windows_updates", sa.Column("support_url", sa.String(), nullable=True))
    op.add_column("inventory_windows_updates", sa.Column("update_id", sa.String(), nullable=True))
    op.add_column(
        "inventory_windows_updates", sa.Column("revision_number", sa.Integer(), nullable=True)
    )
    op.add_column(
        "inventory_windows_updates", sa.Column("deployment_source", sa.String(), nullable=True)
    )
    op.add_column(
        "inventory_windows_updates", sa.Column("package_identity", sa.String(), nullable=True)
    )
    op.add_column(
        "inventory_windows_updates", sa.Column("is_security_update", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "inventory_windows_updates", sa.Column("is_critical_update", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "inventory_windows_updates", sa.Column("is_cumulative_update", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "inventory_windows_updates", sa.Column("is_driver_update", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "inventory_windows_updates", sa.Column("is_feature_update", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "inventory_windows_updates", sa.Column("is_preview_update", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "inventory_windows_updates",
        sa.Column("is_servicing_stack_update", sa.Boolean(), nullable=False),
    )
    op.drop_index(
        op.f("ix_inventory_windows_updates_kb_id"), table_name="inventory_windows_updates"
    )
    op.create_index(
        op.f("ix_inventory_windows_updates_hotfix_id"),
        "inventory_windows_updates",
        ["hotfix_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_windows_updates_update_id"),
        "inventory_windows_updates",
        ["update_id"],
        unique=False,
    )
    op.drop_column("inventory_windows_updates", "status")
    op.drop_column("inventory_windows_updates", "install_date")
    op.drop_column("inventory_windows_updates", "kb_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventory_windows_updates",
        sa.Column("kb_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "inventory_windows_updates",
        sa.Column(
            "install_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "inventory_windows_updates",
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_index(
        op.f("ix_inventory_windows_updates_update_id"), table_name="inventory_windows_updates"
    )
    op.drop_index(
        op.f("ix_inventory_windows_updates_hotfix_id"), table_name="inventory_windows_updates"
    )
    op.create_index(
        op.f("ix_inventory_windows_updates_kb_id"),
        "inventory_windows_updates",
        ["kb_id"],
        unique=False,
    )
    op.drop_column("inventory_windows_updates", "is_servicing_stack_update")
    op.drop_column("inventory_windows_updates", "is_preview_update")
    op.drop_column("inventory_windows_updates", "is_feature_update")
    op.drop_column("inventory_windows_updates", "is_driver_update")
    op.drop_column("inventory_windows_updates", "is_cumulative_update")
    op.drop_column("inventory_windows_updates", "is_critical_update")
    op.drop_column("inventory_windows_updates", "is_security_update")
    op.drop_column("inventory_windows_updates", "package_identity")
    op.drop_column("inventory_windows_updates", "deployment_source")
    op.drop_column("inventory_windows_updates", "revision_number")
    op.drop_column("inventory_windows_updates", "update_id")
    op.drop_column("inventory_windows_updates", "support_url")
    op.drop_column("inventory_windows_updates", "installation_state")
    op.drop_column("inventory_windows_updates", "installed_on")
    op.drop_column("inventory_windows_updates", "installed_by")
    op.drop_column("inventory_windows_updates", "classification")
    op.drop_column("inventory_windows_updates", "description")
    op.drop_column("inventory_windows_updates", "hotfix_id")
    # ### end Alembic commands ###
